// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flightbooking.Models;

#nullable disable

namespace flightbooking.Migrations
{
    [DbContext(typeof(bookingcontext))]
    partial class bookingcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("flightbooking.Models.airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirlineId"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.HasKey("AirlineId");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            Country = "USA",
                            Logo = "skyfly.png",
                            Name = "SkyFly",
                            Rating = 4.5
                        },
                        new
                        {
                            AirlineId = 2,
                            Country = "Germany",
                            Logo = "airwave.png",
                            Name = "AirWave",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            AirlineId = 3,
                            Country = "UK",
                            Logo = "bluewings.png",
                            Name = "BlueWings",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            AirlineId = 4,
                            Country = "Spain",
                            Name = "turkish",
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("flightbooking.Models.booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeatsBooked")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            BookingId = 1,
                            BookingDate = new DateTime(2026, 1, 18, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(3014),
                            SeatsBooked = 2,
                            Status = "Confirmed",
                            TripId = 1,
                            UserId = 1
                        },
                        new
                        {
                            BookingId = 2,
                            BookingDate = new DateTime(2026, 1, 18, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(3019),
                            SeatsBooked = 1,
                            Status = "Confirmed",
                            TripId = 2,
                            UserId = 2
                        },
                        new
                        {
                            BookingId = 3,
                            BookingDate = new DateTime(2026, 1, 18, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(3023),
                            SeatsBooked = 3,
                            Status = "Confirmed",
                            TripId = 3,
                            UserId = 3
                        },
                        new
                        {
                            BookingId = 4,
                            BookingDate = new DateTime(2026, 1, 18, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(3027),
                            SeatsBooked = 2,
                            Status = "Confirmed",
                            TripId = 4,
                            UserId = 1
                        },
                        new
                        {
                            BookingId = 5,
                            BookingDate = new DateTime(2026, 1, 18, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(3031),
                            SeatsBooked = 1,
                            Status = "Confirmed",
                            TripId = 5,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("flightbooking.Models.trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            TripId = 1,
                            AirlineId = 1,
                            ArrivalDateTime = new DateTime(2026, 1, 25, 21, 39, 17, 550, DateTimeKind.Local).AddTicks(2952),
                            AvailableSeats = 100,
                            DepartureDateTime = new DateTime(2026, 1, 25, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(2906),
                            FromCity = "New York",
                            Price = 1200m,
                            ToCity = "London"
                        },
                        new
                        {
                            TripId = 2,
                            AirlineId = 2,
                            ArrivalDateTime = new DateTime(2026, 1, 21, 16, 39, 17, 550, DateTimeKind.Local).AddTicks(2959),
                            AvailableSeats = 50,
                            DepartureDateTime = new DateTime(2026, 1, 21, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(2957),
                            FromCity = "Berlin",
                            Price = 350m,
                            ToCity = "Paris"
                        },
                        new
                        {
                            TripId = 3,
                            AirlineId = 3,
                            ArrivalDateTime = new DateTime(2026, 1, 29, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(2964),
                            AvailableSeats = 80,
                            DepartureDateTime = new DateTime(2026, 1, 28, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(2962),
                            FromCity = "London",
                            Price = 2000m,
                            ToCity = "Tokyo"
                        },
                        new
                        {
                            TripId = 4,
                            AirlineId = 4,
                            ArrivalDateTime = new DateTime(2026, 1, 23, 17, 39, 17, 550, DateTimeKind.Local).AddTicks(2969),
                            AvailableSeats = 60,
                            DepartureDateTime = new DateTime(2026, 1, 23, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(2967),
                            FromCity = "Madrid",
                            Price = 400m,
                            ToCity = "Rome"
                        },
                        new
                        {
                            TripId = 5,
                            AirlineId = 2,
                            ArrivalDateTime = new DateTime(2026, 2, 2, 20, 39, 17, 550, DateTimeKind.Local).AddTicks(2974),
                            AvailableSeats = 90,
                            DepartureDateTime = new DateTime(2026, 2, 2, 14, 39, 17, 550, DateTimeKind.Local).AddTicks(2972),
                            FromCity = "Paris",
                            Price = 1500m,
                            ToCity = "Dubai"
                        });
                });

            modelBuilder.Entity("flightbooking.Models.user", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("phonenum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "yafa@mail.com",
                            Name = "yafa",
                            Password = "1234",
                            Role = 0,
                            phonenum = "12345678"
                        },
                        new
                        {
                            UserId = 2,
                            Email = "doha@mail.com",
                            Name = "doha",
                            Password = "1234",
                            Role = 1,
                            phonenum = "87654321"
                        },
                        new
                        {
                            UserId = 3,
                            Email = "ahmad@mail.com",
                            Name = "ahmad",
                            Password = "1234",
                            Role = 0,
                            phonenum = "12885678"
                        },
                        new
                        {
                            UserId = 4,
                            Email = "diana@mail.com",
                            Name = "Diana",
                            Password = "1234",
                            Role = 0,
                            phonenum = "17345675"
                        });
                });

            modelBuilder.Entity("flightbooking.Models.booking", b =>
                {
                    b.HasOne("flightbooking.Models.trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("flightbooking.Models.user", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("flightbooking.Models.trip", b =>
                {
                    b.HasOne("flightbooking.Models.airline", "Airline")
                        .WithMany()
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });
#pragma warning restore 612, 618
        }
    }
}
